; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericCH32V003F4P6]
platform = ch32v
board = genericCH32V003F4P6
framework = noneos-sdk


build_flags = -Os                   ; Main flag: Optimize for smallest size. (Usually default)
              -flto                 ; Enable Link-Time Optimization. Can significantly reduce size.
              
              ; --- Linker Flags ---
              -ffunction-sections   ; Place each function in its own section
              -fdata-sections       ; Place each data item in its own section
              -Wl,--gc-sections     ; Linker: "Garbage Collect" unused sections (requires the two flags above)
              -Wl,--wrap=_write
          
              ; --- C++ Specific (Good to have even in C projects if C++ lib is linked) ---
              -fno-exceptions       ; Disable C++ exceptions
          
              ; --- CH32V/RISC-V Specific ---
              -march=rv32ecxw       ; Ensure "C" (Compressed) and "E" (Embedded) extensions are used
              -mabi=ilp32e          ; Use the embedded ABI
              -msmall-data-limit=8  ; Use sdata section for small global variables
              -msave-restore
              --specs=nano.specs --specs=nosys.specs